### PR TITLE
Viscosity splitting, TimeStepGizmo, and linear LHS viscosity/diffusivity closure

### LINKED ISSUE #16: Split viscosity for stabilizing LES time stepping
@wenegrat and I talked about implementing a `split viscosity' method for stabilizing time-stepping. 

Essentially, we would like to allow the user to specify some constant 'spliting viscosity' (or diffusivity) in the construction of an `EddyViscosityClosure` that is added to the left side of an equation and subtracted from the right side. 

For example, introducing diffusivity splitting into the buoyancy equation produces

```
b_t + κ_split Δb + ... = ... + ∇ · ( κ_sgs - κ_split ∇b)
```

@wenegrat has found this technique allows larger time-steps and increases numerical stability.

### PR DESCRIPTION
**Pull request by glwagner**
This PR expands the scope of the `EddyViscosityClosure` to allow linear LHS terms. It uses this functionality to implement a 'viscosity splitting' technique to stabilize LES time-stepping (at the cost of accuracy). Viscosity splitting can be used with `AnisotropicMinimumDissipation` for example, by initializing the closure as

```python
closure = dedaLES.AnisotropicMinimumDissipation(ν_split=1e-2, κ_split=1e-2)
```

These parameters add a constant viscosity and diffusivity to the LHS of the appropriate `dedalus` equation, and subtract the constant value from the nonlinear subgrid-scale viscosity and diffusivity on the RHS. This resolves #16.

There is also a new class called [`TimeStepGizmo`](https://github.com/glwagner/dedaLES/blob/35b13a85d4a53efbbb7ad37918955dda81b70891/dedaLES/utils.py#L80) that subclasses `dedalus`' `CFL` class. The new class permits 'diffusivities' to be added to a time-step condition, in addition to velocities. For example:

```python
dt_gizmo = dedaLES.TimeStepGizmo(model.solver, initial_dt=initial_dt, cadence=dt_cadence, max_change=1.5, safety=dt_safety)
dt_gizmo.add_velocities(('u', 'v', 'w'))
dt_gizmo.add_diffusivity('ν_sgs')
dt_gizmo.add_diffusivity('κb_sgs')
```

and then

```python
while model.solver.ok:
    dt = dt_gizmo.compute_dt()
    model.solver.step(dt)
```

similar to `dedalus`' `CFL` class.

Finally, there are new 'benchmarks' for Rayleigh-Benard convection and 'free convection'. These are somewhat incomplete. However, I recommend merging this pull request to master and continuing to work on the benchmarks in the future.

### CODE REVIEW

**Comment by kburns** [comment]
I think the "add_diffusivity" method would be a good thing to add upstream to the Dedalus CFL method!

**Comment by glwagner** [comment]
If only I knew mercurial 😏

**Comment by glwagner** [comment]
@wenegrat can you confirm that my implementation of the splitting viscosity works as expected for your problem? It doesn't seem to stabilize time-stepping for my problem, unfortunately.

**Comment by wenegrat** [comment]
Yeah I'm working on this now. I also seem to be having some trouble...

**Comment by glwagner** [comment]
Do you mind sending a link to your implementation? I might be able to spot the error by comparing what we've done.

**Comment by kburns** [comment]
Happy to add it to dedalus if you don't want to bother with mercurial, etc..  Leaving TimeStepGizmo in for now makes sense, then once we issue a new dedalus build to pip with the change, we could pull it out?

**Comment by wenegrat** [comment]
Hi Greg,

Sorry everything is a mess on my end so it's not easy to share. However
after some quick tests, I believe the issue is that if we write
(closures.py line 131):

(nu_sgs - nu_split)*Sij

This (presumably) gets parsed as nu_sgs*Sij - nu_split*Sij, and the first
term can still blowup. If instead the change is implemented on for example
line 243:

problem.substitutions['ν_sgs'] = "(Δ0**2 + (C_poin*Δ)**2) * sqrt(2*tr_S2) -
" + str(self.ν_split)

The problem appears to be stabilized.

Does this make sense/sound plausible? Not sure, but in testing it this
change does seem to stabilize things.

I doubt that this exact change is the most elegant way to deal with this,
as for example nu_sgs can now be < 0, which messes with calculating the CFL.

Jacob

**Comment by glwagner** [comment]
That's interesting. I'm surprised that change makes a difference! I'll experiment.

I think it's actually a feature (rather than a bug) that the total value of `ν_sgs` is changed --- it makes sense to use the 'adjusted' value of the viscosity to determine time-stepping since, after all, that *is* the effective viscosity that will limit the magnitude of the time-step. It's not a huge issue that the viscosity is negative --- we can add `abs(ν_sgs)` as the diffusivity to `TimeStepGizmo` if we need to.

The only slightly irritating thing about this implementation is that splitting must be implemented manually for each closure.

**Comment by kburns** [comment]
I think the parser should respect the parenthesis if you write "(nu_sgs - nu_split)*Sij" and calculate the difference first.  If not, and rewriting the terms like that really makes a difference to stability, there may be something funky going on and we should get a test case that really isolates it.

**Comment by glwagner** [comment]
I finally found a case of 'successful stabilization' in the currently implemented method between cases 1 and 3 [in this script for convection into a stratified fluid](https://github.com/glwagner/BoundaryLayerLES/blob/15a378254b91cde70e4b5142d7582e6bc945d417/destabilizing_buoyancy_flux/mixed_layer/mixed_layer_convection.py#L48). This can be run with 

```python3 mixed_layer_convection.py ConstantSmagorinsky case```

where `case=1` or `case=3` accordingly. It is interesting to me that either a smaller or larger splitting viscosity is unstable for this setup. Perhaps this is not too surprising --- presumably a caveat with splitting is that it can actually end up *de*-stabilizing the time-stepping if the splitting viscosity is too large (which would result in a large negative viscosity on the RHS). Choosing a good splitting viscosity may be difficult (as @wenegrat hints).

One reason to see a difference between the current implementation and @wenegrat's suggestion is if adaptive time-stepping is being used with a diffusivity criterion (as `TimeStepGizmo` implements). Results can then differ because the time-step stability criterion will be correctly calculated if `ν_split` is included as part of `ν_sgs`. So we must take care to compare cases with the same time-step.

**Comment by kburns** [comment]
Just a note that I'd recommend playing with different time steppers a bit too with these tests -- particularly trying 2nd order SBDF and RK schemes.  The higher order SBDF schemes can have some weird tilmestep restrictions, if I remember correctly.

**Comment by glwagner** [comment]
I'm merging this for now. We can continue to explore splitting in future development.

@kburns, a conversation with @jm-c suggests that SBDF is particularly bad for stability with diffusive-type terms. RK222 may be better a better choice moving forward. @jm-c also suggests that many people will use a lower-order time-stepping scheme (like Foward Euler) specifically just for the LES closure, while stepping forward other terms in the momentum equation with a backwards differencing scheme. The logic is that the error between the LES equations and Navier-Stokes associated with the LES closure will dwarf any numerical error associated with time-stepping of the closure terms (but it's unclear how well-supported this opinion is).

**Pull request merged**
